version: '3.7'


services:

  # portainer:
  #   image: portainer/portainer
  #   container_name: portainer
  #   restart: unless-stopped
  #   ports:
  #     - 9000:9000
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - ./portainer:/data

  dev:
    build:
      context: .
      dockerfile: dev.dockerfile
    image: hiveeyes/dev:latest
    volumes:
      - ./:/src/terkin-datalogger
    stdin_open: true
    tty: true
    ports: 
      - 8080:80

  build:
    image: hiveeyes/dev:latest
    restart: unless-stopped
    volumes:
      - ../terkin-datalogger:/opt/terkin-datalogger
    command: ""

  daemon:
    build:
      context: .
      dockerfile: daemon.dockerfile
    volumes:
      - ./src/settings.py:/opt/terkin-datalogger/settings.py:ro
    image: hiveeyes/daemon:latest
    ports: 
      - 8080:80

